FROM node:alpine as builder
ENV NODE_ENV production
WORKDIR '/app'
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx as production
ENV NODE_ENV production
EXPOSE 80
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf